print("To find sum of two numbers")
First_number = input("enter the 1st number : ")
Second_number = input("enter the 2nd number : ")
sum = (float(First_number) + float(Second_number))
print("sum = ", sum)
input()
